version: "3.3"

services:
  job-interview-backend-dev:
    build: .
    container_name: job-interview-backend-dev
    # image: ghcr.io/grandmember/job-interview-backend:amd64
    restart: 'no'
    ports:
      - "3001:3001"
    networks:
      - default
    environment:
      PORT: ${PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      TZ: ${TZ}
      MONGODB_URL: ${MONGODB_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION_MINUTES: ${JWT_ACCESS_EXPIRATION_MINUTES}
      JWT_REFRESH_EXPIRATION_DAYS: ${JWT_REFRESH_EXPIRATION_DAYS}
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: ${JWT_RESET_PASSWORD_EXPIRATION_MINUTES}
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: ${JWT_VERIFY_EMAIL_EXPIRATION_MINUTES}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME}
      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS}
      DEFAULT_ADMIN_EMAIL: ${DEFAULT_ADMIN_EMAIL}
      DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD}

    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

    logging:
      driver: "json-file"
      options:
        max-size: "512m"
